```{r}
source(here::here("src", "setup.R"), echo = FALSE)
```

<!----------------------------------------------------------------------------->
<!----------------------------------------------------------------------------->
# I. Data:
***

```{r}
(optical_density <- load_od_data())
```

<!----------------------------------------------------------------------------->
<!----------------------------------------------------------------------------->
# II. Analysis:
***

<!----------------------------------------------------------------------------->
## 1. Separately:
***

**Temporary**

```{r}
make_mod_od <- function(data) {
  glmmTMB(
    od_corrected ~ condition + (1 | rat),
    # dispformula = ~ condition,
    family = Gamma("log"),
    data = data,
    REML = TRUE
  )
}

res <- optical_density |>
  group_by(age, location) |> 
  group_map(function(d, g) {
    make_signif_boxplot(make_mod_od(d), xaxis = "condition", subtitle = paste0(g$age, " + ", g$location))
  })

res |> wrap_plots()
```


<!----------------------------------------------------------------------------->
## 2. Combined:
***

<!----------------------------------------------------------------------------->
### Models

**Gamma**

```{r}
mod_od_gamma_tot <- glmmTMB(
  od_corrected ~ condition * age * location + (1 | rat / section),
  # dispformula = ~ age * location,
  family = Gamma("log"),
  data = optical_density,
  REML = TRUE
)

cli_h1("[Parameters]")
parameters(mod_od_gamma_tot)
cli_h1("[Fitness]")
performance(mod_od_gamma_tot)
```

<!----------------------------------------------------------------------------->
### Model Diagnostics

#### Residual diagnostics

```{r fig.width = 10}
check_model(mod_od_gamma_tot)

make_acf_plot(mod_od_gamma_tot)
```

#### Predictive checks

```{r}
mod_od_gamma_tot_dharma <- DHARMa::simulateResiduals(mod_od_gamma_tot, plot = FALSE, n = 300, seed = getOption("seed"))
mod_od_gamma_tot_dharma_t <- t(mod_od_gamma_tot_dharma$simulatedResponse)
```

```{r fig.width = 10}
ppc_plots(mod_od_gamma_tot, simulations = mod_od_gamma_tot_dharma_t, term = "condition")
ppc_plots(mod_od_gamma_tot, simulations = mod_od_gamma_tot_dharma_t, term = "age")
```

```{r fig.width = 10}
ppc_stat_plots(mod_od_gamma_tot, simulations = mod_od_gamma_tot_dharma_t, term = "condition")
ppc_stat_plots(mod_od_gamma_tot, simulations = mod_od_gamma_tot_dharma_t, term = "age")
```

#### Potential outliers

```{r}
get_model_based_outliers(optical_density, mod_od_gamma_tot, mod_od_gamma_tot_dharma, optical_density$od_corrected)
```

<!----------------------------------------------------------------------------->
### Model Analysis

#### Model parameters

**All effects (Wald):**

```{r}
parameters(
  mod_od_gamma_tot, exponentiate = should_exp(mod_od_gamma_tot),
  ci_method = "Wald", p_adjust = "none", summary = TRUE, digits = 3
)
```

**Main effects (Wald):**

```{r}
car::Anova(mod_od_gamma_tot, type = 3)
```

#### Marginal means

**Condition**

```{r}
cli_h1("[Observed]")

distribution_summary(get_data(mod_od_gamma_tot), dvs = find_response(mod_od_gamma_tot), between = "condition")

cli_h1("[Emmeans]")

emmeans(mod_od_gamma_tot, specs = "condition", regrid = "response")
```

**Age**

```{r}
cli_h1("[Observed]")

distribution_summary(get_data(mod_od_gamma_tot), dvs = find_response(mod_od_gamma_tot), between = "age")

cli_h1("[Emmeans]")

emmeans(mod_od_gamma_tot, specs = "age", regrid = "response")
```

**Condition:Age**

```{r}
cli_h1("[Observed]")

distribution_summary(get_data(mod_od_gamma_tot), dvs = find_response(mod_od_gamma_tot), between = c("condition", "age"))

cli_h1("[Emmeans]")

emmeans(mod_od_gamma_tot, specs = ~ condition | age, regrid = "response")
```

#### Contrasts

**Condition**

```{r}
cli_h1("[Link scale]")

emmeans(mod_od_gamma_tot, specs = "condition", type = "response") |> 
  contrast(method = "pairwise", adjust = "none", infer = TRUE)

cli_h1("[Response scale]")

emmeans(mod_od_gamma_tot, specs = "condition", regrid = "response") |>
  contrast(method = "pairwise", adjust = "none", infer = TRUE)
```

```{r fig.width = 4, fig.height = 7}
make_signif_boxplot(mod_od_gamma_tot, xaxis = "condition")
```

**Age**

```{r}
cli_h1("[Link scale]")

emmeans(mod_od_gamma_tot, specs = "age", type = "response") |> 
  contrast(method = "pairwise", adjust = "none", infer = TRUE)

cli_h1("[Response scale]")

emmeans(mod_od_gamma_tot, specs = "age", regrid = "response") |>
  contrast(method = "pairwise", adjust = "none", infer = TRUE)
```

```{r fig.width = 4, fig.height = 7}
make_signif_boxplot(mod_od_gamma_tot, xaxis = "age")
```

**Condition:Stage**

```{r}
cli_h1("[Link scale]")

emmeans(mod_od_gamma_tot, specs = ~ condition | age, type = "response") |> 
  contrast(method = "pairwise", adjust = "none", infer = TRUE)

cli_h2("[Interaction]")

emmeans(mod_od_gamma_tot, specs = ~ condition | age, type = "response") |>
  contrast(interaction = "pairwise", by = NULL, adjust = "none", infer = TRUE)

cli_h1("[Response scale]")

emmeans(mod_od_gamma_tot, specs = ~ condition | age, regrid = "response") |>
  contrast(method = "pairwise", adjust = "none", infer = TRUE)

cli_h2("[Interaction]")

emmeans(mod_od_gamma_tot, specs = ~ condition | age, regrid = "response") |>
  contrast(interaction = "pairwise", by = NULL, adjust = "none", infer = TRUE)
```

```{r fig.width = 14, fig.height = 6}
make_signif_boxplot(mod_od_gamma_tot, xaxis = "condition", facet = "age", ncol = 4, max_points = Inf) |> 
  save_png("mod_od_gamma_tot", width = 14, height = 6, display = TRUE)
```

```{r fig.height = 6, fig.width = 14}
make_signif_boxplot_inter(
  mod_od_gamma_tot, pred1 = "condition", pred2 = "location", facet = "age", 
  cluster = "rat", add_cluster_averages = TRUE, ncol = 5, max_points = Inf
) |> 
  save_png("mod_od_gamma_inter", width = 14, height = 6)
```

```{r fig.height = 6, fig.width = 14}
# emmeans(mod_od_gamma_tot, specs = ~ age | location * condition, type = "response") |> 
#   contrast(method = "pairwise", adjust = "none", infer = TRUE)
```

```{r fig.height = 6, fig.width = 14}
make_signif_boxplot_inter(
  mod_od_gamma_tot, pred1 = "age", pred2 = "location", facet = "condition", 
  cluster = "rat", add_cluster_averages = TRUE, ncol = 5, max_points = Inf
) |> 
  save_png("mod_od_gamma_inter_age", width = 14, height = 6)
```

